baseURL = "https://ssadakk.github.io/"
languageCode = "en-US"
title = "My dev space"
theme = "hago"

DefaultContentLanguage = "en"
metaDataFormat = "yaml"
disqusShortname = "My dev space"
googleAnalytics = "UA-XXXXXXXXX-X"
paginate = 4


[Params]
  description = "삽질한 기록들을 모아보자"
  subtitle = "삽질한 기록들을 모아보자"
  logo = "/images/logo.png"
  favicon = "/favicon.ico"
  comments = true

[Author]
  name = "HM Joo"
  website = "https://ssadakk.github.io"