baseURL: https://ssadakk.github.io/
theme: hugo-theme-pure
title: MyDevSpace
# copyright: 
defaultContentLanguage: en  # en/zh/...
# footnoteReturnLinkContents: ↩
# hasCJKLanguage: true
paginate: 7
enableEmoji: true
PygmentsCodeFences: false
googleAnalytics: "G-P1LKR3P67X"      # UA-XXXXXXXX-X 
# disqusShortname: "myblog-yamhhn4gzh" #Look below
permalinks:
  posts: /:year/:month/:filename/

taxonomies:
    category : categories
    tag : tags
    series : series

outputFormats:          # use for search. recommend not to modify 
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
    home: ["HTML","RSS","SearchIndex"]  # recommend not to modify

# sitemap
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

menu:
  main:
    - identifier: home
      name: Home
      title: Home
      url: /
      weight: 1

    - identifier: archives
      name: Archives
      title: Archives
      url: /posts/
      weight: 2

    - identifier: categories
      name: Categories
      title: Categories
      url: /categories/
      weight: 3

    - identifier: tags
      name: Tags
      title: Tags
      url: /tags/
      weight: 4

    # - identifier: about
    #   name: About
    #   title: About
    #   url: /about/
    #   weight: 5

    - identifier: github
      name: Github
      title: Github
      url: https://github.com/ssadakk/
      weight: 6


params:
  since: 2021
  dateFormatToUse: "2006-01-02"
  # enablePostCopyright: true
  # copyright_link: http://creativecommons.org/licenses/by/4.0/deed.zh
  # the directory under content folder that you want to render
  mainSections: ["post"]
  # Enable/Disable menu icons
  # Icon Reference: http://blog.cofess.com/hexo-theme-pure/iconfont/demo_fontclass.html
  enableMathJax: true #Enable mathjax support, to use mathematical notations
  highlightjs:
    langs: ["python", "javascript"] # refer to http://staticfile.org/, search highlight.js, already have highlight.min.js

  tag_cloud:
    min: 8
    max: 20
  # Allows you to specify an override stylesheet
  # put custom.css in $hugo_root_dir/static/
  # customCSS: css/custom.css

  menuIcons:
    enable: true 
    home: icon-home-fill
    archives: icon-archives-fill
    categories: icon-folder
    tags: icon-tags
    repository: icon-project
    books: icon-book-fill
    links: icon-friendship
    about: icon-cup-fill
    github: icon-github

  # profile
  profile:
    enabled: true # Whether to show profile bar
    avatar: avatar.png
    gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
    author: HM J
    author_title: Nobody
    author_description: Someone likes to development
    location: Seoul, Korea
    follow: https://github.com/ssadakk
    # Social Links
    social:
      links:
        github: https://github.com/ssadakk

      link_tooltip: false # enable the social link tooltip, options: true, false
  # Site
  # site:
  #   logo:
  #     enabled: true
  #     width: 40
  #     height: 40
  #     url: favicon.ico
  #   title: Hugo # 页面title
  #   favicon: favicon.ico
  #   board: <p>enjoy~</p> # 公告牌


  # Comment
  comment:
    type: disqus # type disqus/gitalk/valine 启用哪种评论系统
    disqus: "myblog-yamhhn4gzh" # enter disqus shortname here




  # wordcount
  postCount:
    enable: true
    wordcount: false # 文章字数统计
    min2read: true # read time 阅读时长预计

  # config
  config:
    skin: theme-black # theme color default is white. other type [theme-black,theme-blue,theme-green,theme-purple]
    layout: main-center # main-left main-center main-right
    excerpt_link: Read More
    toc: true

  # Sidebar
  sidebar: right

  # Search
  search:
    enable: true # enable search. thanks for https://raw.githubusercontent.com/ppoffice/hexo-theme-icarus/master/source/js/insight.js

  # Sidebar only the following widgets. you can remove any you don't like it.
  widgets:
    - tag_cloud
    - category
    - tag
    - recent_posts

